---
- name: Load environment-specific secrets for Azure
  include_vars:
    file: "secrets/secrets_azure.yaml"
  when: inventory_hostname in groups['azure']

- name: Load environment-specific secrets for AWS
  include_vars:
    file: "secrets/secrets_aws.yaml"
  when: inventory_hostname in groups['aws']

- name: Load environment-specific secrets for GCP
  include_vars:
    file: "secrets/secrets_gcp.yaml"
  when: inventory_hostname in groups['gcp']

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: 
    - default-mysql-client
  tags: install_mysql

- name: Create application directory
  file:
    path: /var/www/webapp
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copy application code
  copy:
    src: app/app.py
    dest: /var/www/webapp/app.py
    owner: www-data
    group: www-data
    mode: '0755'
  when: inventory_hostname not in groups['azure']

- name: Copy application code for Azure
  copy:
    src: app/app_azure.py
    dest: /var/www/webapp/app.py
    owner: www-data
    group: www-data
    mode: '0755'
  when: inventory_hostname in groups['azure']

- name: Copy requirements.txt
  copy:
    src: files/requirements.txt
    dest: /var/www/webapp/requirements.txt
    owner: www-data
    group: www-data
    mode: '0644'

- name: Copy SSL certificate
  copy:
    src: files/DigiCertGlobalRootCA.crt.pem
    dest: /etc/ssl/certs/DigiCertGlobalRootCA.crt.pem
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in groups['azure']

- name: Install Python packages
  pip:
    requirements: /var/www/webapp/requirements.txt

- name: Install Gunicorn globally
  pip:
    name: gunicorn

- name: Configure systemd service for Gunicorn
  template:
    src: templates/gunicorn.service.j2
    dest: /etc/systemd/system/webapp.service
    mode: '0644'

- name: Ensure config.py file exists for web application
  template:
    src: templates/config.py.j2
    dest: /var/www/webapp/config.py
    owner: www-data
    group: www-data
    mode: '0644'

- name: Reload systemd to apply new Gunicorn service
  systemd:
    daemon_reload: yes

- name: Start and enable Gunicorn service
  systemd:
    name: webapp
    state: started
    enabled: yes
