packages:
  - curl
  - python3
  - python3-apt
  - python3-pip
  - vim
  - nmap
  - cron
  - host
  - git

user_accounts:
  - name: artur
    authorized_keys:
      - artur.pub
  - name: ola
    authorized_keys:
      - ola.pub
